"""Bundle agent_src/contract.py + agent_src/m*.py into a single self-contained agent.py.

Usage: .venv/bin/python tools/build_agent.py [--out PATH]

Rules:
  * lines whose trailing '#' comment ends with 'bundle:strip' are dropped
    (e.g. '# bundle:strip' or '# noqa: F401,F403  bundle:strip');
  * every 'from __future__ import ...' line is dropped, one 'from __future__ import annotations'
    is emitted at the very top (after the header docstring);
  * modules are concatenated in order: contract.py, then m*.py sorted by filename;
  * missing modules are skipped with a warning (partial builds work);
  * result must py_compile and must not contain forbidden tokens.
"""
from __future__ import annotations

import argparse
import py_compile
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "agent_src"
DEFAULT_OUT = ROOT / "agent.py"

# Modules the full agent is expected to contain (missing ones only produce a warning).
EXPECTED_MODULES = (
    "m10_dataview.py",
    "m20_prior.py",
    "m30_arm_model.py",
    "m40_simulator.py",
    "m50_allocator.py",
    "m60_packer.py",
    "m70_planner.py",
    "m80_llm.py",
    "m85_guardrails.py",
    "m90_orchestrator.py",
)

HEADER = '''"""
Beeline tariff campaigns agent / Агент тарифных кампаний Beeline.

RU: байесовский агент — пилоты по knowledge gradient, лагранжева аллокация бюджета и охвата,
точный симулятор скоринга и LLM-слой (Pydantic AI) для гипотез и риск-ревью; всегда возвращает валидные кампании.
EN: Bayesian pilot-driven agent (knowledge-gradient pilots, Lagrangian money/reach allocation,
exact scoring simulator, optional Pydantic AI hypothesis/risk-review layer); always returns valid campaigns.

AUTO-GENERATED by tools/build_agent.py from agent_src/ — do not edit by hand.
"""
'''

FORBIDDEN = [
    (re.compile(r"__closure__"), "__closure__"),
    (re.compile(r"^\s*(import\s+gc\b|from\s+gc\s+import)", re.M), "import gc"),
    (re.compile(r"\bgc\.\w"), "gc.*"),
    (re.compile(r"inspect", re.I), "inspect"),
    (re.compile(r"internals", re.I), "internals"),
]

# A line is stripped when its trailing comment ends with 'bundle:strip'
# (covers both '# bundle:strip' and '# noqa: F401,F403  bundle:strip').
_STRIP_RE = re.compile(r"#[^\n]*\bbundle:strip\s*$")
_FUTURE_RE = re.compile(r"^\s*from\s+__future__\s+import\b")


def _warn(msg: str) -> None:
    sys.stderr.write(f"[build_agent] WARNING: {msg}\n")


def module_files(src: Path = SRC) -> list[Path]:
    """contract.py first, then m*.py sorted; warns about missing expected modules."""
    files: list[Path] = []
    contract = src / "contract.py"
    if contract.exists():
        files.append(contract)
    else:
        _warn("agent_src/contract.py missing")
    mods = sorted(src.glob("m*.py"))
    present = {p.name for p in mods}
    for name in EXPECTED_MODULES:
        if name not in present:
            _warn(f"module {name} missing - skipped")
    files.extend(mods)
    return files


def strip_source(text: str) -> list[str]:
    """Drop bundle:strip and __future__ lines."""
    out: list[str] = []
    for line in text.splitlines():
        if _STRIP_RE.search(line):
            continue
        if _FUTURE_RE.match(line):
            continue
        out.append(line)
    return out


def bundle(files: list[Path]) -> str:
    """Concatenate stripped module sources into one source string."""
    parts = [HEADER, "from __future__ import annotations", ""]
    for path in files:
        parts.append("")
        parts.append(f"# {'=' * 70}")
        parts.append(f"# agent_src/{path.name}")
        parts.append(f"# {'=' * 70}")
        parts.extend(strip_source(path.read_text(encoding="utf-8")))
    return "\n".join(parts).rstrip() + "\n"


def check_forbidden(source: str) -> list[str]:
    """Return list of forbidden-token hits as 'token (line N)'."""
    hits: list[str] = []
    for rx, label in FORBIDDEN:
        for m in rx.finditer(source):
            line_no = source.count("\n", 0, m.start()) + 1
            hits.append(f"{label} (line {line_no})")
    return hits


def build(out: Path = DEFAULT_OUT, src: Path = SRC) -> Path:
    """Build agent.py; raises RuntimeError on forbidden tokens or compile error."""
    source = bundle(module_files(src))
    hits = check_forbidden(source)
    if hits:
        raise RuntimeError("forbidden tokens in bundle: " + ", ".join(hits))
    tmp = out.with_name(out.name + ".tmp")
    tmp.write_text(source, encoding="utf-8")
    try:
        with tempfile.TemporaryDirectory() as td:
            py_compile.compile(str(tmp), cfile=str(Path(td) / "agent.pyc"), doraise=True)
    except py_compile.PyCompileError as exc:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(f"bundle does not compile: {exc.msg}") from exc
    tmp.replace(out)
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args(argv)
    try:
        path = build(args.out)
    except RuntimeError as exc:
        sys.stderr.write(f"[build_agent] ERROR: {exc}\n")
        return 1
    n_lines = path.read_text(encoding="utf-8").count("\n")
    sys.stdout.write(f"[build_agent] wrote {path} ({n_lines} lines)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
